{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sophia-runtime-adapters.serviceAccountName" . }}
  labels:
    {{- include "sophia-runtime-adapters.labels" . | nindent 4 }}
{{- end -}}
